# Generated by Django 3.2.9 on 2021-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=350)),
            ],
        ),
    ]
